// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCrGV5yvUfFo249tBYFAW98_Vk2YoVz1g',
    appId: '1:201126940133:web:46ee910ff1bca26e31b30c',
    messagingSenderId: '201126940133',
    projectId: 'blablagithub',
    authDomain: 'blablagithub.firebaseapp.com',
    storageBucket: 'blablagithub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Idyug4YZGmoT-lY7-iBmVzdiPaVy6WI',
    appId: '1:201126940133:android:2353d336d05e15c331b30c',
    messagingSenderId: '201126940133',
    projectId: 'blablagithub',
    storageBucket: 'blablagithub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfXoczrihZxWuoeNgY59auSqtreOXl1PQ',
    appId: '1:201126940133:ios:197bbd1b7a4c0d8c31b30c',
    messagingSenderId: '201126940133',
    projectId: 'blablagithub',
    storageBucket: 'blablagithub.appspot.com',
    androidClientId:
        '201126940133-iv4o3vlt572gotbosidvhu71ckd8p0ql.apps.googleusercontent.com',
    iosClientId:
        '201126940133-ii9i6vl9v7bl34078m4k1t7c1cu7f3vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.blablagithub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfXoczrihZxWuoeNgY59auSqtreOXl1PQ',
    appId: '1:201126940133:ios:0be2149a4fa1328531b30c',
    messagingSenderId: '201126940133',
    projectId: 'blablagithub',
    storageBucket: 'blablagithub.appspot.com',
    androidClientId:
        '201126940133-iv4o3vlt572gotbosidvhu71ckd8p0ql.apps.googleusercontent.com',
    iosClientId:
        '201126940133-n65be5ufodh32q4vrthshdv3ellq4lnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.blablagithub.RunnerTests',
  );
}
